In [1]:
import numpy as np

In [2]:
x = np.array([1,7,2])
y = np.array([5,2,1])

In [3]:
x+y

array([6, 9, 3])

In [4]:
x-y

array([-4,  5,  1])

In [5]:
x*y

array([ 5, 14,  2])

In [12]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

In [13]:
def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

In [14]:
# 두 벡터 사이의 각도
def angle(x,y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta