In [2]:
import numpy as np
x = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])

In [3]:
y = np.array([[0,1],
             [1,-1],
             [-2,1]])

In [4]:
# 행렬의 곱셈
x @ y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [6]:
# 행렬의 내적
X = np.array([[1,-2,3],
             [7,5,0],
             [-2,-1,2]])
Y = np.array([[0,1,-1],
             [1,-1,0]])
np.inner(X,Y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [7]:
# 역행열 구하기
np.linalg.inv(X)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [8]:
# 항등행렬
X @ np.linalg.inv(X)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  0.00000000e+00,  1.00000000e+00]])

In [10]:
# 유사역행렬
Y = np.array([[0,1],
             [1,-1],
             [-2,1]])
np.linalg.pinv(Y)

array([[ 5.00000000e-01,  1.11022302e-16, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [11]:
np.linalg.pinv(Y) @ Y

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

In [14]:
# Scikit Learn 을 활용한 회귀분석
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
y_test = model.predict(x_test)

NameError: name 'x_test' is not defined

In [15]:
# Moore-Penrose 역행렬
X_ = np.array([np.append(x,[1]) for x in X])
beta = np.linalg.pinv(X_) @ y
y_test = np.append(x, [1]) @ beta

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 10)